### ISSUE TITLE
Contributor information seems to be out of date

### ISSUE THREAD

**Issue by evan2645** [jtimberman/ossec-cookbook#12]
From the commit history, as well as the opscode cookbook site, it appears that this cookbook is no longer maintained by opscode. The contributor guidelines, however, still indicate that an opscode COOK ticket should be raised, though this cookbook is no longer on the list of components in Jira. Therefor, I have submitted two PR's without any associated tickets (against the current contribution guidelines).

**Comment by tas50** [comment]
Docs are now updated
