### ISSUE TITLE
Bump Ossec version to 2.8.1

### ISSUE THREAD

**Issue by shortdudey123** [jtimberman/ossec-cookbook#39]
This discussion was started in PR https://github.com/jtimberman/ossec-cookbook/pull/31
Moving here

PRs related to update
https://github.com/jtimberman/ossec-cookbook/pull/31
https://github.com/jtimberman/ossec-cookbook/pull/38

**Comment by shortdudey123** [comment]
Others PR's discussed as being merged as part of version bump...
https://github.com/jtimberman/ossec-cookbook/pull/33
https://github.com/jtimberman/ossec-cookbook/pull/34

**Comment by ChronusAdmin** [comment]
Any updates on this??

**Comment by hitesh-kumarr** [comment]
Any updates on this??

**Comment by tas50** [comment]
Ossec is coming from the upstream repo now so you should always get the latest.
