### ISSUE TITLE
SSH Data Bag

### ISSUE THREAD

**Issue by Natrinicle** [jtimberman/ossec-cookbook#40]
Following the cookbook installation instructions, I created a databag called ossec and an ssh item inside of it. I cannot however get it to work correctly though after trying the following:

Copy output of ruby -e 'puts IO.read("/tmp/id_rsa")' directly between the "" for "privkey": "" which causes an error when I attempt to knife upload data bag.

Copy output of ruby -e 'puts IO.read("/tmp/id_rsa")' | tr -d '\n' allows the privkey section to be accepted during a knife upload but causes the clients to error with ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: '10.9.8.210'. in the client and ossec-remoted(1403): ERROR: Incorrectly formated message from '10.9.8.20'. in the server which I believe indicates a bad SSH key.

Can someone show me an example of a working ssh data bag item or tell me what I'm doing wrong?

**Comment by huwge** [comment]
Try:
cat /tmp/id_rsa |perl -pe 's!(\x0d)?\x0a!\\n!g'
and
cat /tmp/id_rsa.pub |perl -pe 's!(\x0d)?\x0a!\\n!g'

and use the output of each command as the data you put into the data bag

**Comment by Natrinicle** [comment]
When I do a "knife upload data bag from file data_bags/ossec/ssh.json", I get:

ERROR: data_bags/ossec/ssh.json failed to write: Parse error reading JSON: lexical error: invalid character inside string.
          ----BEGIN RSA PRIVATE KEY----- MIIJKQIBAAKCAgEAvbVSM0of/fee7
                     (right here) ------^

With the (right here) pointing to the newline.

**Comment by jtimberman** [comment]
You need to replace the actual new lines with `\n`.

**Comment by Natrinicle** [comment]
Ah, that seems to have gotten the SSH key uploaded. Thanks for the tip jtimberman. Still getting the incorrectly formatted message error but I'll keep poking at the server/client
