### ISSUE TITLE
Init.d script missing

### ISSUE THREAD

**Issue by elmic11111** [jtimberman/ossec-cookbook#43]
So after running the Server install for OSSEC, it reported that it couldn't start. Here the error from chef log. I checked and ossec didn't create a init.d script. 

[2015-03-23T14:21:22+00:00] ERROR: service[ossec] (ossec::default line 76) had an error: Chef::Exceptions::Service: service[ossec]: unable to locate the init.d script!

Looking at the OSSEC information, I found this in the install fill:

The script will create everything in /var/ossec and try to create the initialization script in your system (/etc/rc.local or /etc/rc.d/init.d/ossec). If the init script is not created, make sure to follow the instructions from the install.sh to make OSSEC HIDS start during the boot. To start it by hand, just run /var/ossec/bin/ossec-control start

**Comment by tas50** [comment]
This seems to be resolved in master right now
