### ISSUE TITLE
TemplateError when setting node['ossec']['user']['white_list'] in role definition

### ISSUE THREAD

**Issue by muddman** [jtimberman/ossec-cookbook#45]
I added a single white_list entry to the client role and got the following error:

* template[/var/chef/cache/ossec-hids-2.8.1/etc/preloaded-vars.conf] action create

    Error executing action `create` on resource 'template[/var/chef/cache/ossec-hids-2.8.1/etc/preloaded-vars.conf]'
    

    Chef::Mixin::Template::TemplateError

    undefined method `join' for "10.10.10.10":String

    Resource Declaration:

   In /var/chef/cache/cookbooks/ossec/recipes/default.rb

     34: template "#{Chef::Config[:file_cache_path]}/#{ossec_dir}/etc/preloaded-vars.conf" do
     35:   source "preloaded-vars.conf.erb"
     36:   variables :ossec => node['ossec']['user']
     37: end
     38:

.....

    Template Context:

    on line #61
     59: <% end -%>
     60: <% unless @ossec['white_list'].empty? -%>
     61: USER_WHITE_LIST="<%= @ossec['white_list'].join(' ') %>"
     62: <% else -%>
     63: USER_WHITE_LIST="<%= node['ipaddress'] %>"

Running handlers:
[2015-05-08T11:45:30-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-08T11:45:30-04:00] ERROR: Exception handlers complete
[2015-05-08T11:45:30-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.2194893 seconds
[2015-05-08T11:45:30-04:00] ERROR:

Chef::Mixin::Template::TemplateError (undefined method `join' for "10.10.10.10":String) on line #61:

 59: <% end -%>
 60: <% unless @ossec['white_list'].empty? -%>
 61: USER_WHITE_LIST="<%= @ossec['white_list'].join(' ') %>"
 62: <% else -%>
 63: USER_WHITE_LIST="<%= node['ipaddress'] %>"

**Comment by jtimberman** [comment]
You need to specify `node['ossec']['white_list']` as an array.

* https://github.com/jtimberman/ossec-cookbook/blob/master/attributes/default.rb#L58
