### ISSUE TITLE
Server/WUI installs without error, but no web , no VirtualHosts

### ISSUE THREAD

**Issue by jmstallard** [jtimberman/ossec-cookbook#50]
Hello:
just installed on AWS/CentOS 6.5 without errors and can't seem to get the web to start.
Get this after converging & restarting httpd:

Starting httpd: [Thu Oct 15 10:09:51 2015] [warn] NameVirtualHost *:80 has no VirtualHosts

Runlist:
ossec_server
apache2 #3.1.0
apache2::mod_php5
ossec::wui

Any ideas what's up?

**Comment by jmstallard** [comment]
Appears to be iptables... its working now.
but I have other issues...
ossec-remoted doesn't start up, even though I configured an agent, thus queue access errors on agent.
client.key wasn't found in /etc/
it is in /var/ossec/etc
same with ar.conf
Also, the .htpasswd password was commented out.
hmm.
Running on AWS, I'll get test-kitchen running & update.

**Comment by tas50** [comment]
WUI has been removed from the cookbook since the project is abandoned.  I'm going to close this now.
