### ISSUE TITLE
Problem to runt the role ossec_server

### ISSUE THREAD

**Issue by jlruizmlg** [jtimberman/ossec-cookbook#63]
hello, first at all thanks for the this cookbook look amazing,

Im trying to runt the rolse ossec_server but i have this error

```
Net::HTTPServerException
------------------------
400 "Bad Request"

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ossec/recipes/server.rb:28:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ossec/recipes/server.rb:

 21:
 22:  ssh_hosts = []
 23:
 24:  search_string = 'ossec:[* TO *]'
 25:  search_string << " AND chef_environment:#{node['ossec']['server_env']}" if node['ossec']['server_env']
 26:  search_string << " AND NOT role:#{node['ossec']['server_role']} AND NOT fqdn:#{node['fqdn']}"
 27:
 28>> search(:node, search_string) do |n|
 29:    ssh_hosts << n['ipaddress'] if n['keys']
 30:
 31:    execute "#{node['ossec']['agent_manager']} -a --ip #{n['ipaddress']} -n #{n['fqdn'][0..31]}" do
 32:      not_if "grep '#{n['fqdn'][0..31]} #{n['ipaddress']}' #{node['ossec']['dir']}/etc/client.keys"
 33:    end
 34:  end
 35:
 36:  template '/usr/local/bin/dist-ossec-keys.sh' do
 37:    source 'dist-ossec-keys.sh.erb'
```

and the /var/chef/cache/chef-stacktrace.out say this

```
Generated at 2016-03-30 21:41:53 +0000
Net::HTTPServerException: 400 "Bad Request"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:145:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/http.rb:110:in `get'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/search/query.rb:158:in `call_rest_service'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/search/query.rb:87:in `search'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/dsl/data_query.rb:39:in `search'
/var/chef/cache/cookbooks/ossec/recipes/server.rb:28:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context.rb:332:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context.rb:167:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:509:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:277:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:445:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:435:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:435:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/client.rb:424:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:50:in `load'
/bin/chef-client:50:in `<main>'
```

Im using the same example than you have in your Readme

```
name "ossec_server"
description "OSSEC Server"
run_list("recipe[ossec::server]")
override_attributes(
  "ossec" => {
    "conf" => {
      "server" => {
        "global" => {
          "email_to" => "ossec@yourdomain.com",
          "smtp_server" => "smtp.yourdomain.com"
        }
      }
    }
  }
)
```

really im not sure what's im doing wrong, any help?

thanks.

**Comment by chewi** [comment]
Please don't contact me privately like you did, that isn't very appropriate in free software projects and this isn't even my cookbook. I'm not overly familiar with the server recipe. You'll need to provide a much fuller trace than that for us to see what's really wrong.

**Comment by jlruizmlg** [comment]
Sorry about that, i saw a nice pull request from you in a fork repo, anyway you are right,

thanks for your help.

**Comment by chewi** [comment]
Given that you haven't set `node['ossec']['server_env']` or changed `node['ossec']['server_role']`, I would guess that `node['fqdn']` is blank, which can happen if you haven't configured `/etc/hosts` properly. The exact way to do this varies between distros but check that the `127.0.0.1` line doesn't start have `localhost` as the first entry.

**Comment by jlruizmlg** [comment]
Thanks for your reply 
my /etc/hosts is easy:
```
127.0.0.1   ossec_manager localhost localhost.localdomain localhost4 localhost4.localdomain4
::1            ossec_manager localhost localhost.localdomain localhost6 localhost6.localdomain6
```
so you mean in the server role look like that:

```
name "ossec_server"
description "OSSEC Server"
run_list("recipe[ossec::server]")
override_attributes(
  "ossec" => {
  "server_env":  "server"
    "conf" => {
      "server" => {
        "global" => {
          "email_to" => "ossec@yourdomain.com",
          "smtp_server" => "smtp.yourdomain.com"
        }
      }
    }
  }
)
```
```
[root@ossec_manager user]# hostname
ossec_manager
[root@ossec_manager user]# hostname -f
ossec_manager
```

**Comment by chewi** [comment]
It's not that then. You shouldn't need to set server_env. I'm afraid I don't know what the problem is as I prefer to use my authd stuff from #48 instead of this recipe.

**Comment by jlruizmlg** [comment]
i will try that, usually we work with agent_auth, this #48 was the reason to contact with you, thanks!

**Comment by jlruizmlg** [comment]
hi again @chewi sorry for ask again, after use your #48 as you say in your README if i set the agent_server_ip attribute manually the recipe don't try to use agent_auth

this is my role

```
{
  "name": "ossec_client",
  "description": "OSSEC Client Agents",
  "json_class": "Chef::Role",
  "default_attributes": {

  },
  "override_attributes": {
    "ossec": {
      "agent_server_ip": "172.16.141.133",
      "conf": {
        "agent": {
          "syscheck": {
            "frequency": 321
          }
        }
      }
    }
  },
  "chef_type": "role",
  "run_list": [
    "recipe[ossec::client]"
  ],
  "env_run_lists": {

  }
}
```

sorry for bother you.

**Comment by chewi** [comment]
I don't understand how you thought that.

> Set the agent_server_ip attribute manually and this recipe will attempt to register with the given server running ossec-authd.

Don't use the ossec::client recipe here, use ossec::agent_auth instead. I know this is confusing and that's why I've asked for the SSH method to be dropped or at least for the recipes to be renamed.

**Comment by jlruizmlg** [comment]
Oh understood, now works nice in agent and manager.

on the other hand, the certs for authd are not created by the recipe, right? so they need to be created or moved to the ossec folder

**Comment by chewi** [comment]
Correct, I find certificate creation within cookbooks to be a bit impractical. If you want this then I suggest creating a wrapper cookbook. Glad you got it working.

**Comment by jlruizmlg** [comment]
ok perfect thanks again! and sorry for the first contact!

**Comment by jlruizmlg** [comment]
sorry @chewi one last question, how do you manage the local_rules.xml??

**Comment by chewi** [comment]
I haven't got very far into actually configuring OSSEC yet. I suppose the Gyoku stuff could have gone further and rendered rule files too, probably through an LWRP. On the other hand, don't the rule files tend to be quite static? Even the custom ones?

**Comment by tas50** [comment]
I'm jumping in a bit late here, but I'd like to make most of this cookbook a LWRP.  We've learned a lot in the last few years and attribute driven cookbooks still have a lot of issues in the wrapper cookbook model.  Pure library cookbooks are much more powerful for complex software packages like OSSEC

**Comment by jlruizmlg** [comment]
yes and no, the local_rules many times are useful to rewrite other rules, also you might need to create a new rules, etc.
on the other hand, do you know RESTful API? you can do many things in ossec like add new agents without ossec-auth or agent-auth.

If i can help with ossec, happy to help :)

**Comment by jlruizmlg** [comment]
@chewi sorry one last question, when i try to use a different repo than atomic or my own rpms for the server in the ```common``` recipe i have the next error

```
manager.yokatan.com     # Declared in /var/chef/cache/cookbooks/ossec/recipes/common.rb:46:in `from_file'
manager.yokatan.com
manager.yokatan.com     file("/var/ossec/etc/ossecs.conf") do
manager.yokatan.com       action [:create]
manager.yokatan.com       retries 0
manager.yokatan.com       retry_delay 2
manager.yokatan.com       default_guard_interpreter :default
manager.yokatan.com       declared_type :file
manager.yokatan.com       cookbook_name "ossec"
manager.yokatan.com       recipe_name "common"
manager.yokatan.com       owner "root"
manager.yokatan.com       group "ossec"
manager.yokatan.com       mode 288
manager.yokatan.com       manage_symlink_source true
manager.yokatan.com       content #<Chef::DelayedEvaluator:0x00000003e59248@/var/chef/cache/cookbooks/ossec/recipes/common.rb:53>

manager.yokatan.com       path "/var/ossec/etc/ossecs.conf"
manager.yokatan.com     end
manager.yokatan.com
manager.yokatan.com
manager.yokatan.com Running handlers:
manager.yokatan.com [2016-04-01T13:25:32-05:00] ERROR: Running exception handlers
manager.yokatan.com Running handlers complete
manager.yokatan.com [2016-04-01T13:25:32-05:00] ERROR: Exception handlers complete
manager.yokatan.com Chef Client failed. 1 resources updated in 50 seconds
manager.yokatan.com [2016-04-01T13:25:32-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
manager.yokatan.com [2016-04-01T13:25:32-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
manager.yokatan.com [2016-04-01T13:25:32-05:00] ERROR: file[/var/ossec/etc/ossecs.conf] (ossec::common line 46) had an error: NoMethodError: undefined method `to_hash' for nil:NilClass
manager.yokatan.com [2016-04-01T13:25:32-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The folder /var/ossec/etc is the same, same permissions than atomic rpms, all the same but still having this error.

i dont understand from where came the line ```manager.yokatan.com       atomic_update true```because also i delete all reference to install through repository, i install the rpm manually and later try to control with chef.

any idea? 

thanks again

**Comment by chewi** [comment]
My guess is that your RPM does not include `/etc/ossec-init.conf` with a `TYPE=` line. That would cause `node['ossec']['install_type']` to be nil and [line 56](https://github.com/yakara-ltd/ossec-cookbook/blob/b00b396306b59bf66e1eff50ea8d029179a8d15c/recipes/common.rb#L56) to fail. You need this line set to either `server` or `agent`, depending on the RPM. Another way might be to set `node['ossec']['install_type']` as an override attribute but I haven't tried that.

We use our own RPMs too, hosted on packagecloud, but these are based on the Atomic ones. The Atomic repository will always be added by the repository receipe and we do not try to prevent this. Instead, we add our own repository beforehand with the packagecloud cookbook and set its priority to 1 so it is chosen over Atomic. I forget exactly how you do that and I don't have the code to hand.

**Comment by jlruizmlg** [comment]
yes thanks, i had two errors, 
1.- my rpms don't left ossec-init.conf in /etc/, left in other folder
2.- to me server is manager in this ossec-init.com.

I just change the common and the attributes/default.rb to manager.

My specs are based in wazuh of course :) thanks again for your help
